name: Deploy to Azure Container Instances

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name maxkerkhofacrinfrafontys

    - name: Build and push Docker image
      run: |
        docker build -t maxkerkhofacrinfrafontys.azurecr.io/apache-webapp:v1 .
        docker push maxkerkhofacrinfrafontys.azurecr.io/apache-webapp:v1

    - name: Delete existing Azure Container Instance
      run: |
        az container delete --name apache-container --resource-group max.infra --yes || true

    - name: Deploy new Azure Container Instance
      run: |
        az container create --resource-group max.infra \
          --name apache-container \
          --image maxkerkhofacrinfrafontys.azurecr.io/apache-webapp:v1 \
          --cpu 1 --memory 1.5 \
          --registry-login-server maxkerkhofacrinfrafontys.azurecr.io \
          --registry-username ${{ secrets.AZURE_REGISTRY_USERNAME }} \
          --registry-password ${{ secrets.AZURE_REGISTRY_PASSWORD }} \
          --restart-policy Always \
          --ports 80 \
          --os-type Linux \
          --ip-address Public
